# Tarea 01 - Modelos Lineales

## Integrantes

* Centeno Amado Eduardo
* Orozpe Frias Erick Adrian
* Pineda Gaona Maricruz
* Rodriguez Teodores Armando
* Velasco Martell Dayra

## Instrucciones

## Práctica

![img3](Imgs/T01_Inst3.png)

# Librerías

In [1]:
import pandas as pd

# Funciones

In [24]:
def is_na_df(df):
    #Establecemos el resumen de NAs por columna
    na_summary = (
        df.isna().sum()
        .reset_index()
        .rename(columns={"index": "columna", 0: "n_missing"})
    )

    #Tomamos totales y prporciones
    na_summary["total"] = len(df)
    na_summary["prop_missing"] = na_summary["n_missing"] / na_summary["total"]
    na_summary["prop_original"] = 1 - na_summary["prop_missing"]

    #Filtramos solo columnas con al menos 1 NA
    na_summary = na_summary[na_summary["n_missing"] > 0].reset_index(drop=True)

    #Agregamos fila resumen global
    total_missing = df.isna().sum().sum()
    total_elements = df.size
    prop_missing_global = total_missing / total_elements
    prop_original_global = 1 - prop_missing_global

    resumen = pd.DataFrame({
        "columna": ["TOTAL"],
        "n_missing": [total_missing],
        "total": [total_elements],
        "prop_missing": [prop_missing_global],
        "prop_original": [prop_original_global]
    })

    na_summary = pd.concat([na_summary, resumen], ignore_index=True)

    return na_summary

# Ejercicio 1

In [2]:
diamonds = pd.read_csv(r'https://raw.githubusercontent.com/Wsm-erick/Diplomado/refs/heads/main/Modulo-II/Datasets/diamonds.csv')

In [4]:
diamonds.head(3)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [26]:
# Valores Ausentes
is_na_df(diamonds)

  columna  n_missing   total  prop_missing  prop_original
0   TOTAL          0  539400           0.0            1.0

In [22]:
y = diamonds.loc[:, ["price"]]
X = diamonds.loc[:, [x for x in diamonds.columns if x != 'price']]

In [18]:
num_cols = X.select_dtypes(['float','int']).columns

In [19]:
cat_cols = X.select_dtypes(['object']).columns

In [20]:
cat_cols

Index(['cut', 'color', 'clarity'], dtype='object')

In [23]:
y

       price
0        326
1        326
2        327
3        334
4        335
...      ...
53935   2757
53936   2757
53937   2757
53938   2757
53939   2757

[53940 rows x 1 columns]