# Bibliotecas

In [3]:
import os

In [1]:
import pandas as pd

# Ejercicio 1

## EDA

In [2]:
PATH = r'https://raw.githubusercontent.com/Wsm-erick/Diplomado/refs/heads/main/Modulo-III/Datasets'

In [4]:
encuesta = pd.read_csv(os.path.join(PATH, 'data_practica_encuesta.csv'))

In [5]:
encuesta.shape

(25976, 14)

In [6]:
encuesta.head()

,Id,Servicio wifi a bordo,Hora de salida/llegada conveniente,Facilidad de reserva en línea,Ubicación de la puerta,Alimentos y bebidas,Embarque en línea,Comodidad del asiento,Entretenimiento a bordo,Servicio a bordo,Servicio de sala de piernas,Manejo de equipaje,Servicio de facturación,Limpieza
0,19556,5,4,3,4,3,4,3,5,5,5,5,2,5
1,90035,1,1,3,1,5,4,5,4,4,4,4,3,5
2,12360,2,0,2,4,2,2,2,2,4,1,3,2,2
3,77959,0,0,0,2,3,4,4,1,1,1,1,3,4
4,36875,2,3,4,3,4,1,2,2,2,2,2,4,4

In [22]:
encuesta.columns.tolist()

['Id',
 'Servicio wifi a bordo',
 'Hora de salida/llegada conveniente',
 'Facilidad de reserva en línea',
 'Ubicación de la puerta',
 'Alimentos y bebidas',
 'Embarque en línea',
 'Comodidad del asiento',
 'Entretenimiento a bordo',
 'Servicio a bordo',
 'Servicio de sala de piernas',
 'Manejo de equipaje',
 'Servicio de facturación',
 'Limpieza']

In [21]:
encuesta.loc[:,'Servicio wifi a bordo':].describe().T

,count,mean,std,min,25%,50%,75%,max
Servicio wifi a bordo,25976.0,2.724746,1.335384,0.0,2.0,3.0,4.0,5.0
Hora de salida/llegada conveniente,25976.0,3.046812,1.533371,0.0,2.0,3.0,4.0,5.0
Facilidad de reserva en línea,25976.0,2.756775,1.412951,0.0,2.0,3.0,4.0,5.0
Ubicación de la puerta,25976.0,2.977094,1.282133,1.0,2.0,3.0,4.0,5.0
Alimentos y bebidas,25976.0,3.215353,1.331506,0.0,2.0,3.0,4.0,5.0
Embarque en línea,25976.0,3.261665,1.355536,0.0,2.0,4.0,4.0,5.0
Comodidad del asiento,25976.0,3.449222,1.320090,1.0,2.0,4.0,5.0,5.0
Entretenimiento a bordo,25976.0,3.357753,1.338299,0.0,2.0,4.0,4.0,5.0
Servicio a bordo,25976.0,3.385664,1.282088,0.0,2.0,4.0,4.0,5.0
Servicio de sala de piernas,25976.0,3.350169,1.318862,0.0,2.0,4.0,4.0,5.0
Manejo de equipaje,25976.0,3.633238,1.176525,1.0,3.0,4.0,5.0,5.0
Servicio de facturación,25976.0,3.314175,1.269332,1.0,3.0,3.0,4.0,5.0
Limpieza,25976.0,3.286226,1.319330,0.0,2.0,3.0,4.0,5.0

In [20]:
N = encuesta.shape[0]

print('Proporción de missings...', end='\n\n')

for col in encuesta.columns:
    n = encuesta.loc[:, col].isna().sum()
    print(f'{col} -', n/N)

Proporción de missings...

Id - 0.0
Servicio wifi a bordo - 0.0
Hora de salida/llegada conveniente - 0.0
Facilidad de reserva en línea - 0.0
Ubicación de la puerta - 0.0
Alimentos y bebidas - 0.0
Embarque en línea - 0.0
Comodidad del asiento - 0.0
Entretenimiento a bordo - 0.0
Servicio a bordo - 0.0
Servicio de sala de piernas - 0.0
Manejo de equipaje - 0.0
Servicio de facturación - 0.0
Limpieza - 0.0

No hay valores vacíos.